config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :contacts
end

app/models/contact.rb
class Contact < ApplicationRecord
  TYPE = %w(Business Personal)
  self.inheritance_column = 'type'
  has_many :addresses, dependent: :destroy
  has_many :phones, dependent: :destroy

  accepts_nested_attributes_for :phones
  accepts_nested_attributes_for :addresses

  validates :first_name, :last_name, :age, :email, :type, presence: true
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, if: Proc.new{ |f| f.email.present? }
  validates_uniqueness_of :email, if: Proc.new{ |f| f.email.present? }
  validates_numericality_of :age, less_than_or_equal_to: 100, greater_than: 0, if: Proc.new{ |f| f.age.present? }
  validates :type, inclusion: { in: TYPE }

  # collect all addresses
  def all_addresses
    address = ''
    addresses.each { |addr| address << addr.format << '\n' }
    address
  end

  # collect all phones
  def all_phones
    phones.pluck(:number).join(",")
  end

  # get name
  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # Breadcrumb navigation
  def set_breadcrumbs
    super
    add_breadcrumb 'Contacts Management', contacts_path
  end

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.includes(:addresses, :phones)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    add_breadcrumb 'New Contact', new_contact_path
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
    add_breadcrumb @contact.name
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name,:last_name,:age,:email,:type,
                                      addresses_attributes: [:door_no, :street, :city, :state, :pincode, :landmark, :id],
                                      phones_attributes: [:number, :type_of, :id])
    end
end

app/views/contacts/_form.html.erb
<div class="container">
  <%= form_for contact, html: { class: "form-horizontal contact-form" } do |f| %>
      <%= error_messages_for(f.object) %>
      <div class="form-group <%= form_class(f.object, 'first_name') %>">
        <label class="col-sm-2 control-label">FirstName</label>
        <div class="col-sm-10">
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
      </div>

      <div class="form-group <%= form_class(f.object, 'last_name') %>">
        <label class="col-sm-2 control-label">LastName</label>
        <div class="col-sm-10">
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
      </div>

      <div class="form-group <%= form_class(f.object, 'age') %>">
        <label class="col-sm-2 control-label">Age</label>
        <div class="col-sm-10">
          <%= f.text_field :age, class: "form-control" %>
        </div>
      </div>

      <div class="form-group <%= form_class(f.object, 'email') %>">
        <label class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>

      <div class="form-group <%= form_class(f.object, 'type') %>">
        <label class="col-sm-2 control-label">Type</label>
        <div class="col-sm-10">
          <%= f.select :type, options_for_select(Contact::TYPE,f.object.type), {}, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Address</label>
        <div class="col-sm-10">
          <% addr = contact.addresses.empty? ? contact.addresses.build : contact.addresses %>
          <% addr_count = 0 %>
          <div class="address-input">
            <%= f.fields_for :addresses, addr do |address_form| %>
                  <% addr_count = addr_count + 1 %>
                  <div class="address-lists">
                    <div class="input-group addr-input <%= form_class(address_form.object, 'door_no') %>">
                      <%= address_form.text_field :door_no, class:"form-control", placeholder: 'Flat No, Building Name' %>
                    </div>

                    <div class="input-group addr-input <%= form_class(address_form.object, 'street') %>">
                      <%= address_form.text_field :street, class:"form-control", placeholder: 'Street' %>
                    </div>

                    <div class="input-group addr-input <%= form_class(address_form.object, 'city') %>">
                      <%= address_form.text_field :city, class:"form-control", placeholder: 'City' %>
                    </div>

                    <div class="input-group addr-input <%= form_class(address_form.object, 'state') %>">
                      <%= address_form.text_field :state, class:"form-control", placeholder: 'State' %>
                    </div>

                    <div class="input-group addr-input <%= form_class(address_form.object, 'pincode') %>">
                      <%= address_form.text_field :pincode, class:"form-control", placeholder: 'Pincode' %>
                    </div>

                    <% if action_name == 'edit' || action_name == 'update' %>
                        <button type="button" class="btn btn-success btn-sm btn-add-address" disabled>
                          <span class="glyphicon glyphicon-plus"></span> Add Address
                        </button>
                    <% else %>
                        <% if address_form.object.errors.any? && addr_count == 1 %>
                          <button type="button" class="btn btn-success btn-sm btn-add-address">
                            <span class="glyphicon glyphicon-plus"></span> Add Address
                          </button>
                        <% elsif address_form.object.errors.any? %>
                          <button type="button" class="btn btn-danger btn-sm btn-remove-address">
                            <span class="glyphicon glyphicon-minus"></span> Remove Address
                          </button>
                        <% else %>
                          <button type="button" class="btn btn-success btn-sm btn-add-address">
                            <span class="glyphicon glyphicon-plus"></span> Add Address
                          </button>
                        <% end %>
                    <% end %>
                  </div>
            <% end %>
          </div>
        </div>
      </div>


      <div class="form-group">
        <label class="col-sm-2 control-label">Phone</label>
        <div class="col-sm-10">
          <% phs = contact.phones.empty? ? contact.phones.build : contact.phones %>
          <div class="phone-list">
            <%= f.fields_for :phones, phs do |phone_number_form| %>
                <div class="input-group phone-input">
                  <%= phone_number_form.select :type_of, options_for_select(Phone::TYPE,phone_number_form.object.type_of), {}, class: "phone-type" %>
                  <div class="phone-number <%= form_class(phone_number_form.object, 'number') %>">
                    <%= phone_number_form.text_field :number, class: "form-control", placeholder: "+1 (999) 999 9999" %>
                  </div>
                </div>
            <% end %>
          </div>
          <% if action_name == 'edit' || action_name == 'update' %>
              <button type="button" class="btn btn-success btn-sm btn-add-phone" disabled>
                <span class="glyphicon glyphicon-plus"></span> Add Phone
              </button>
          <% else %>
              <button type="button" class="btn btn-success btn-sm btn-add-phone">
                <span class="glyphicon glyphicon-plus"></span> Add Phone
              </button>
          <% end %>
        </div>
      </div>
      <%= f.submit 'Save', class: 'btn btn-primary' %>
  <% end %>
  <hr>
</div>

app/views/contacts/edit.html.erb
<% content_for(:page_header) do %>
    Edit Contact
<% end %>

<%= render 'form', contact: @contact %>

app/views/contacts/index.html.erb
<% content_for(:page_header) do %>
Contact Management
    <%= link_to 'New Contact', new_contact_path, class: "btn btn-primary" %>
<% end %>

  <table id="contacts" class="display table table-striped table-sm table-hover" cellspacing="0" width="100%" >
    <thead>
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Email</th>
        <th>Type</th>
        <th>Address</th>
        <th>PhoneNumber</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
      <tr class='clickable' data-location='<%= edit_contact_path(contact) %>'>
        <td><%= contact.name %></td>
        <td><%= contact.age %></td>
        <td><%= contact.email %></td>
        <td><%= contact.type %></td>
        <td><%= (contact.all_addresses.gsub('\n', '<br/>')).html_safe %></td>
        <td><%= (contact.all_phones.gsub(',', '<br/>')).html_safe %></td>
        <td><%= link_to 'Delete', contact, method: :delete,class: "btn btn-danger delete-contact" %> | <%= link_to 'View', contact, class: "btn btn-info" %></td>
       </tr>
       <% end %>
     </tbody>
   </table>

  <% content_for(:extra_scripts) do %>

      $(document).ready(function() {
        $('#contacts').DataTable({ responsive:
          true<%= ', searching: false, paging: false, info: false' if @contacts.count <= 10 %>  });
      });

  <% end %>

app/views/contacts/new.html.erb
<% content_for(:page_header) do %>
    New Contact
<% end %>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for(:page_header) do %>
    (<td><strong><%= @contact.type %></strong></td>) Contact
<% end %>

<div style="float:right">
<%= link_to 'Edit', edit_contact_path(@contact), class: "btn btn-primary" %> |
<%= link_to 'Back', contacts_path, class: "btn btn-info" %>
</div>

<div class="container">
  <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Email Details</a>
        </h4>
      </div>
      <div id="collapse1" class="panel-collapse collapse in">
        <div class="panel-body">
          <table class="table table-sm">
            <tbody>
            <tr class="success">
              <th scope="row">1</th>
              <td>Name: </td>
              <td><strong><%= @contact.name %></strong></td>
            </tr>
            <tr class="info">
              <th scope="row">2</th>
              <td>Age: </td>
              <td><strong><%= @contact.age %></strong></td>
            </tr>
            <tr class="success">
              <th scope="row">3</th>
              <td>Email: </td>
              <td><strong><%= @contact.email %></strong></td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Address Details</a>
        </h4>
      </div>
      <div id="collapse2" class="panel-collapse collapse">
        <div class="panel-body">
          <table class="table table-sm">
            <tbody>
            <% @contact.addresses.each_with_index do |address,index| %>
                <tr class=<%= ((index+1) % 2) == 0 ? "success" : "info" %>>
                  <th scope="row"><%= index+1 %></th>
                  <td>Address<%= index+1 %>: </td>
                  <td><strong><%= address.format.html_safe %></strong></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">Phone Details</a>
        </h4>
      </div>
      <div id="collapse3" class="panel-collapse collapse">
        <div class="panel-body">
          <table class="table table-sm">
            <tbody>
            <% @contact.phones.each_with_index do |phone,index| %>
                <tr class=<%= ((index+1) % 2) == 0 ? "success" : "info" %>>
                  <th scope="row"><%= index+1 %></th>
                  <td><%= phone.type_of %>: </td>
                  <td><strong><%= phone.number %></strong></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>