config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :contacts
end

app/views/layouts/_delete.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body" align="center">
        <strong><%= content_for?(:delete_message) ? yield(:delete_message) : "Are you sure you want to delete this record?" %></strong>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit("Delete", class: "btn btn-danger") %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/" title='Automation Onboarding Admin Panel'>
      <img style="max-height:55px; margin-top: -7px;" <%= image_tag "oracle.png" %>
    </a>
  </div>

  <div class="nav navbar-nav">
    <h3>Contact Mail / Phone / Address</h3>

  </div>

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav in" id="side-menu">
        <li>
          <a href="/">
            <i class="fa fa-dashboard fa-fw"></i>
            Dashboard</a>
        </li>
        <li>
          <a href="#"><i class="fa fa-tasks fa-fw"></i> Contact Management <span class="fa arrow"></span></a>
          <ul class="nav nav-second-level collapse">
            <li>
              <%= link_to 'Contact List', contacts_path %>
            </li>
          </ul>
        </li>
        <li>
          <a href="#">
            <i class="fa  fa-info-circle fa-fw"></i>
            About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_title.html.erb
<ol class="breadcrumb">
  <!-- <%= yield(:breadcrumb_items) %> -->
  <% if @breadcrumbs.count > 1 %>
    <% @breadcrumbs.each_with_index do |breadcrumb, inx| %>
      <% if @breadcrumbs.size-1 != inx %>
    <li class="breadcrumb-item"><%= link_to(breadcrumb[:name], breadcrumb[:url]) %></li>
      <% else %>
    <li class="breadcrumb-item active"><%= breadcrumb[:name] %></li>
      <% end %>
    <% end %>
  <% end %>
</ol>
<div class="row">
  <div class="col-lg-12">
    <div class="page-header">
      <div class="row">
        <h1><div class='col-xs-12 col-md-7 col-lg-7 text-left small bottom-align-text' style="margin-top: 10px;">
          <%= content_for?(:page_header) ? yield(:page_header) : Faker::StarWars.character + ' from ' + Faker::StarWars.planet %>
        </div></h1>
        <div class='col-xs-12 col-md-5 col-lg-5 text-right' style="height: 100%">
          <%= content_for?(:action_buttons) ? yield(:action_buttons) : "" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactHistory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <%= content_for?(:title) ? yield(:title) : "" %>
  </title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "cATS" %>">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%# Devise:
  Ensure you have flash messages in app/views/layouts/application.html.erb
  for notice and alert: %>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4" style="text-align:center;">
        <h1>cATS - Cloud Automation Tooling System</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Please Sign In</h3>
          </div>
          <div class="panel-body">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_tag type: 'text/javascript' do -%>
  <%= raw render 'layouts/messages_js.coffee' %>
<% end %>
</html>

app/views/layouts/oracle_admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <%= content_for?(:title) ? yield(:title) : "cATS" %>
  </title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Automation Onboarding Admin Panel" %>">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag params[:controller], media: 'all' if Rails.application.assets.find_asset params[:controller] %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= [controller_name, action_name].join(' ').gsub(/\_/, '-') %>">
  <div id="wrapper" class="">
    <%= render 'layouts/navbar' %>
  </div>

  <div id="page-wrapper">
    <%= render 'layouts/title' %>
    <%= yield %>
  </div>
</body>
<%= javascript_include_tag 'application' %>
<%= javascript_include_tag params[:controller] if Rails.application.assets.find_asset params[:controller] %>
<%= javascript_tag type: 'text/javascript' do -%>
  <%= content_for?(:extra_scripts) ? yield(:extra_scripts) : nil %>
  <%= raw render 'layouts/messages_js.coffee' %>
<% end %>
</html>